;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #171520
background-alt = #373B41
foreground = #C5C8C6
primary = #F0C674
secondary = #8ABEB7
alert = #A54242
disabled = #707880

color4= #C7A4DA
color2 = #DFA986
color3 = #9AD2A1
color1 = #DA819C
color5 = #87B9E2

dark = #080808
grey = #555169
white = #f0f0f0
darkblue = #043F6D

[bar/main]
width = 100%
height = 22pt
radius = 0

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt
border-color = #00000000

margin-bottom = 0

padding-left = 0
padding-right = 0

module-margin-right = 0

separator =
separator-foreground = ${colors.disabled}

font-0 = Fira Code Nerd Font;3
font-1 = Fira Code Nerd Font:pixelsize=15;3
font-2 = Fira Code Nerd Font:pixelsize=18;5
font-3 = Fira Code Nerd Font:pixelsize=28;11
font-4 = Fira Code Nerd Font:pixelsize=18;5
modules-left = launcher lsep0 cpu lsep1 memory lsep2 xworkspaces lsep3
modules-center = date
modules-right =  rsep0 pulseaudio rsep1 backlight rsep2 battery rsep3

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-position = right
tray-background = ${colors.color4}
tray-foreground = ${colors.dark}
tray-maxsize = 24

wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

override-redirect = true

[module/rsep0]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color5}
;content-background = ${colors.color5}
content-padding = 0

[module/rsep1]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color3}
content-background = ${colors.color5}
content-padding = 0

[module/rsep2]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color2}
content-background = ${colors.color3}
content-padding = 0

[module/rsep3]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color4}
content-background = ${colors.color2}
content-padding = 0

[module/lsep3]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color5}
;content-background = ${colors.color5}
content-padding = 0

[module/lsep2]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color3}
content-background = ${colors.color5}
content-padding = 0

[module/lsep1]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color2}
content-background = ${colors.color3}
content-padding = 0

[module/lsep0]
type = custom/text
content = %{T4}%{T-}
content-foreground = ${colors.color4}
content-background = ${colors.color2}
content-padding = 0

[module/launcher]
type = custom/text
content = %{T3} 󰣇 %{T-}

; "content" has the same properties as "format-NAME"
content-background = ${colors.color4}
content-foreground = ${colors.dark}
content-padding = 0

; "click-(left|middle|right)" will be executed using "/bin/sh -c $COMMAND"
click-left = albert toggle
click-middle = xdotool key super+d
;click-right = notify-send right

; "scroll-(up|down)" will be executed using "/bin/sh -c $COMMAND"
;scroll-up = notify-send scroll up
;scroll-down = notify-send scroll down

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 99

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 15

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = BAT0
adapter = ADP0

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 5

; see "man date" for details on how to format the time string
; NOTE: if you want to use syntax tags here you need to use %%{...}
; Default: %H:%M:%S
time-format = %H:%M

; Available tags:
;   <label-charging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-charging>
format-charging = %{T2} <animation-charging> %{T-}<label-charging>

; Available tags:
;   <label-discharging> (default)
;   <bar-capacity>
;   <ramp-capacity>
;   <animation-discharging>
format-discharging = %{T2} <ramp-capacity>%{T-} <label-discharging>

; Available tags:
;   <label-full> (default)
;   <bar-capacity>
;   <ramp-capacity>
format-full = <label-full>

; Format used when battery level drops to low-at
; If not defined, format-discharging is used instead.
; Available tags:
;   <label-low>
;   <animation-low>
;   <bar-capacity>
;   <ramp-capacity>
; New in version 3.6.0
format-low =  <label-low> <animation-low>

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current charge rate in watts)
label-charging =  %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
label-discharging =  %percentage%%

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
label-full = %{T2} 󰂄%{T-} FULL

; Available tokens:
;   %percentage% (default) - is set to 100 if full-at is reached
;   %percentage_raw%
;   %time%
;   %consumption% (shows current discharge rate in watts)
; New in version 3.6.0
label-low = %{T2} 󰂃%{T-}

; Only applies if <ramp-capacity> is used
ramp-capacity-0 = 󰁺
ramp-capacity-1 = 󰁻
ramp-capacity-2 = 󰁼
ramp-capacity-3 = 󰁽
ramp-capacity-4 = 󰁾
ramp-capacity-5 = 󰁿
ramp-capacity-6 = 󰂀
ramp-capacity-7 = 󰂁
ramp-capacity-8 = 󰂂
ramp-capacity-9 = 󰁹
; Only applies if <bar-capacity> is used
bar-capacity-width = 10

; Only applies if <animation-charging> is used
animation-charging-0 = 󰢜 
animation-charging-1 = 󰂆
animation-charging-2 = 󰂇
animation-charging-3 = 󰂈
animation-charging-4 = 󰢝
animation-charging-5 = 󰂉
animation-charging-6 = 󰢞
animation-charging-7 = 󰂊
animation-charging-8 = 󰂋
animation-charging-9 = 󰂅

; Framerate in milliseconds
animation-charging-framerate = 750

; Only applies if <animation-discharging> is used
animation-discharging-0 = 
animation-discharging-1 = 
animation-discharging-2 = 
animation-discharging-3 = 
animation-discharging-4 = 
; Framerate in milliseconds
animation-discharging-framerate = 500

; Only applies if <animation-low> is used
; New in version 3.6.0
animation-low-0 = LOW!
animation-low-1 = %{F#DFA986}LOW!%{F-}
animation-low-framerate = 200

format-full-foreground = ${colors.dark}
format-low-foreground = ${colors.dark}
format-charging-foreground = ${colors.dark}
format-discharging-foreground = ${colors.dark}

format-full-background = ${colors.color2}
format-low-background = ${colors.color2}
format-charging-background = ${colors.color2}
format-discharging-background = ${colors.color2}

[module/backlight]
type = internal/xbacklight

; XRandR output to get get values from
; Default: the monitor defined for the running bar
output = DP-0

; Create scroll handlers used to set the backlight value
; Default: true
enable-scroll = true

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format =  <ramp> <label> 
format-background = ${colors.color3}
format-foreground = ${colors.dark}

; Available tokens:
;   %percentage% (default)
label = %percentage%%

; Only applies if <ramp> is used
ramp-0 = 󰃚 
ramp-1 = 󰃛
ramp-2 = 󰃜
ramp-3 = 󰃝
ramp-4 = 󰃞
ramp-5 = 󰃟
ramp-6 = 󰃠

; Only applies if <bar> is used
bar-width = 20
bar-indicator =  
bar-fill = ─
bar-empty = ─

[module/xworkspaces]
type = internal/xworkspaces

; Only show workspaces defined on the same output as the bar
;
; Useful if you want to show monitor specific workspaces
; on different bars
;
; Default: false
pin-workspaces = true

; Create click handler used to focus desktop
; Default: true
enable-click = true

; Create scroll handlers used to cycle desktops
; Default: true
enable-scroll = false

; Reverse the scroll direction
; Default: false
; New in version 3.6.0
reverse-scroll = true

; icon-[0-9]+ = <desktop-name>;<icon>
; Map desktop names to some icon. The icon is then available in the %icon% token
; NOTE: The desktop name needs to match the name configured by the WM
; You can get a list of the defined desktop names using:
; $ xprop -root _NET_DESKTOP_NAMES
; NOTE: Neither <desktop-name> nor <icon> can contain a semicolon (;)
icon-0 = 1;%{B#DA819C} %{T5} 󰹑 %{B-}%{B#DFA986}%{F#DA819C}%{T4}%{T-}%{F-}%{B-}
icon-1 = 2;%{B#DFA986} %{T5}󰹑 %{B-}%{B#9AD2A1}%{F#DFA986}%{T4}%{T-}%{F-}%{B-}
icon-2 = 3;%{B#9AD2A1} %{T5}󰹑 %{B-}%{B#87B9E2}%{F#9AD2A1}%{T4}%{T-}%{F-}%{B-}
icon-3 = 4;%{B#87B9E2} %{T5}󰹑 %{B-}%{B#171520}%{F#87B9E2}%{T4}%{T-}%{F-}%{B-}

; icon-4 = web;♞
; icon-default = ♟

; Available tags:
;   <label-monitor>
;   <label-state> - gets replaced with <label-(active|urgent|occupied|empty)>
; Default: <label-state>
format = <label-state>

; Available tokens:
;   %name%
; Default: %name%
label-monitor = %name%

; Used for the currently selected workspaces
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-active = %name%
label-active-foreground = ${colors.dark}
label-active-background = ${colors.color5}
label-active-underline = ${colors.darkblue}
label-active-padding = 1

; Used for workspaces at least one window
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-occupied = %name%
; label-occupied-underline = #555555
label-occupied-padding = 1
label-occupied-foreground = ${colors.dark}
label-occupied-background = ${colors.color5}

; Used for workspaces containing a window that is demanding attention (has the
; urgent bit set)
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-urgent = %icon%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-underline = #9b0a20
label-urgent-padding = 1

; Used for workspaces without windows
; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %nwin% (New in version 3.6.0)
; Default: %icon% %name%
label-empty = %name%
label-empty-foreground = ${colors.dark}
label-empty-background = ${colors.color5}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

; Sink to be used, if it exists (find using `pacmd list-sinks`, name field)
; If not, uses default sink
; sink = alsa_output.pci-0000_12_00.3.analog-stereo

; Use PA_VOLUME_UI_MAX (~153%) if true, or PA_VOLUME_NORM (100%) if false
; Default: true
use-ui-max = false

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 1
; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = %{T3}<ramp-volume> %{T-}<label-volume>

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-volume = %percentage%%

; Available tokens:
;   %percentage% (default)
;   %decibels%
label-muted = %{T3} 󰸈 %{T-}
;label-muted-foreground = #FFFFFF

; Only applies if <ramp-volume> is used
ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾

; Right and Middle click
click-right = pavucontrol
; click-middle = 

format-volume-background = ${colors.color5}
format-muted-background = ${colors.color5}
format-muted-foreground = ${colors.dark}
format-volume-foreground = ${colors.dark}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-foreground = ${colors.dark}
format-background = ${colors.color3}
label = %percentage_used%%
label-foreground = ${colors.dark}
label-background = ${colors.color3}
format = %{A1:kitty -e bpytop &:}RAM <label>%{A}

[module/cpu]
type = internal/cpu
interval = 2
format = %{A1:kitty -e bpytop &:}CPU <label>%{A}
label = %percentage%%
format-foreground = ${colors.dark}
format-background = ${colors.color2}
label-foreground = ${colors.dark}
bar-load-indicator =
bar-load-width = 5
bar-load-foreground-0 = #55aa55
bar-load-foreground-1 = #557755
bar-load-foreground-2 = #f5a70a
bar-load-foreground-3 = #ff5555
bar-load-fill = ▐
bar-load-empty = ▐
bar-load-empty-foreground = #444444

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:alacritty -e nmtui &:}%{F#F0C674}%{T2}󰖩 %{T-}%{F-}%essid%%{A}
label-disconnected = %{A1:alacritty -e nmtui &:}%{F#F0C674}%{T2}󰖪%{T-}%{F-}%{A}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{A1:alacritty -e nmtui &:}%{T2}󰈁%{T-} %ifname%%{A}
label-disconnected = %{A1:alacritty -e nmtui &:}%{T2}󰈂%{T-}%{A}

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %{T4}%{F#C7A4DA}%{T-}%{F-}%{B#C7A4DA}%{F#080808}%a %b %e%{F-}%{B-}%{T4}%{F#C7A4DA}%{T-}%{F-} %{T4}%{F#C7A4DA}%{T-}%{F-}%{B#C7A4DA}%{F#080808}%H:%M:%S%{F-}%{B-}%{T4}%{F#C7A4DA}%{T-}%{F-}

label = %date%
label-foreground = ${colors.color4}

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
